/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as SplatRouteImport } from './app/routes/$'
import { Route as R404RouteImport } from './app/routes/404'
import { Route as AboutRouteImport } from './app/routes/about'
import { Route as MusicFunRouteImport } from './app/routes/music-fun'
import { Route as MyPlaylistPageRouteImport } from './app/routes/my-playlist-page'
import { Route as OauthCallbackRouteImport } from './app/routes/oauth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicFunRoute = MusicFunRouteImport.update({
  id: '/music-fun',
  path: '/music-fun',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPlaylistPageRoute = MyPlaylistPageRouteImport.update({
  id: '/my-playlist-page',
  path: '/my-playlist-page',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/music-fun': typeof MusicFunRoute
  '/my-playlist-page': typeof MyPlaylistPageRoute
  '/oauth/callback': typeof OauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/music-fun': typeof MusicFunRoute
  '/my-playlist-page': typeof MyPlaylistPageRoute
  '/oauth/callback': typeof OauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/music-fun': typeof MusicFunRoute
  '/my-playlist-page': typeof MyPlaylistPageRoute
  '/oauth/callback': typeof OauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/404'
    | '/about'
    | '/music-fun'
    | '/my-playlist-page'
    | '/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/404'
    | '/about'
    | '/music-fun'
    | '/my-playlist-page'
    | '/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/404'
    | '/about'
    | '/music-fun'
    | '/my-playlist-page'
    | '/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  MusicFunRoute: typeof MusicFunRoute
  MyPlaylistPageRoute: typeof MyPlaylistPageRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-fun': {
      id: '/music-fun'
      path: '/music-fun'
      fullPath: '/music-fun'
      preLoaderRoute: typeof MusicFunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-playlist-page': {
      id: '/my-playlist-page'
      path: '/my-playlist-page'
      fullPath: '/my-playlist-page'
      preLoaderRoute: typeof MyPlaylistPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  MusicFunRoute: MusicFunRoute,
  MyPlaylistPageRoute: MyPlaylistPageRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
